# Generated by Django 3.2.3 on 2021-05-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
                ('porcentaje_ddhh', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
